name: healthyme_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

      
  flutter_svg: ^2.0.7 
  english_words: ^4.0.0
  provider: ^6.1.5
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  csv: ^5.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: any
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets: 
      - lib/assets/home_icon.svg
      - lib/assets/chat_icon.svg
      - lib/assets/ingredient_dataset.csv
